language: node_js
node_js:
  - "12.10.0"
cache:
  directories:
  - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: .docz/dist
  on:
    branch: master
